// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: stakeholders/stakeholders-service.proto

package stakeholders

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationRequest) Reset() {
	*x = RegistrationRequest{}
	mi := &file_stakeholders_stakeholders_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationRequest) ProtoMessage() {}

func (x *RegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_stakeholders_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationRequest.ProtoReflect.Descriptor instead.
func (*RegistrationRequest) Descriptor() ([]byte, []int) {
	return file_stakeholders_stakeholders_service_proto_rawDescGZIP(), []int{0}
}

func (x *RegistrationRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegistrationRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegistrationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegistrationRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_stakeholders_stakeholders_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_stakeholders_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_stakeholders_stakeholders_service_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthenticationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticationResponse) Reset() {
	*x = AuthenticationResponse{}
	mi := &file_stakeholders_stakeholders_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationResponse) ProtoMessage() {}

func (x *AuthenticationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_stakeholders_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationResponse.ProtoReflect.Descriptor instead.
func (*AuthenticationResponse) Descriptor() ([]byte, []int) {
	return file_stakeholders_stakeholders_service_proto_rawDescGZIP(), []int{2}
}

func (x *AuthenticationResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthenticationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetAllUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUsersRequest) Reset() {
	*x = GetAllUsersRequest{}
	mi := &file_stakeholders_stakeholders_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUsersRequest) ProtoMessage() {}

func (x *GetAllUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_stakeholders_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUsersRequest.ProtoReflect.Descriptor instead.
func (*GetAllUsersRequest) Descriptor() ([]byte, []int) {
	return file_stakeholders_stakeholders_service_proto_rawDescGZIP(), []int{3}
}

// Poruka koja predstavlja jednog korisnika
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	IsBlocked     bool                   `protobuf:"varint,5,opt,name=isBlocked,proto3" json:"isBlocked,omitempty"`
	FirstName     string                 `protobuf:"bytes,6,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName      string                 `protobuf:"bytes,7,opt,name=lastName,proto3" json:"lastName,omitempty"`
	ProfileImage  string                 `protobuf:"bytes,8,opt,name=profileImage,proto3" json:"profileImage,omitempty"`
	Biography     string                 `protobuf:"bytes,9,opt,name=biography,proto3" json:"biography,omitempty"`
	Motto         string                 `protobuf:"bytes,10,opt,name=motto,proto3" json:"motto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_stakeholders_stakeholders_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_stakeholders_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_stakeholders_stakeholders_service_proto_rawDescGZIP(), []int{4}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *User) GetIsBlocked() bool {
	if x != nil {
		return x.IsBlocked
	}
	return false
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetProfileImage() string {
	if x != nil {
		return x.ProfileImage
	}
	return ""
}

func (x *User) GetBiography() string {
	if x != nil {
		return x.Biography
	}
	return ""
}

func (x *User) GetMotto() string {
	if x != nil {
		return x.Motto
	}
	return ""
}

// Odgovor sa listom korisnika
type GetAllUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllUsersResponse) Reset() {
	*x = GetAllUsersResponse{}
	mi := &file_stakeholders_stakeholders_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllUsersResponse) ProtoMessage() {}

func (x *GetAllUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_stakeholders_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllUsersResponse.ProtoReflect.Descriptor instead.
func (*GetAllUsersResponse) Descriptor() ([]byte, []int) {
	return file_stakeholders_stakeholders_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetAllUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

// Blokiranje korisnika
type BlockUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // id korisnika koji se blokira
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockUserRequest) Reset() {
	*x = BlockUserRequest{}
	mi := &file_stakeholders_stakeholders_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockUserRequest) ProtoMessage() {}

func (x *BlockUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_stakeholders_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockUserRequest.ProtoReflect.Descriptor instead.
func (*BlockUserRequest) Descriptor() ([]byte, []int) {
	return file_stakeholders_stakeholders_service_proto_rawDescGZIP(), []int{6}
}

func (x *BlockUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BlockUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockUserResponse) Reset() {
	*x = BlockUserResponse{}
	mi := &file_stakeholders_stakeholders_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockUserResponse) ProtoMessage() {}

func (x *BlockUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_stakeholders_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockUserResponse.ProtoReflect.Descriptor instead.
func (*BlockUserResponse) Descriptor() ([]byte, []int) {
	return file_stakeholders_stakeholders_service_proto_rawDescGZIP(), []int{7}
}

func (x *BlockUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Deblokiranje korisnika
type UnblockUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // id korisnika koji se deblokira
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockUserRequest) Reset() {
	*x = UnblockUserRequest{}
	mi := &file_stakeholders_stakeholders_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockUserRequest) ProtoMessage() {}

func (x *UnblockUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_stakeholders_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockUserRequest.ProtoReflect.Descriptor instead.
func (*UnblockUserRequest) Descriptor() ([]byte, []int) {
	return file_stakeholders_stakeholders_service_proto_rawDescGZIP(), []int{8}
}

func (x *UnblockUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UnblockUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnblockUserResponse) Reset() {
	*x = UnblockUserResponse{}
	mi := &file_stakeholders_stakeholders_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnblockUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnblockUserResponse) ProtoMessage() {}

func (x *UnblockUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_stakeholders_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnblockUserResponse.ProtoReflect.Descriptor instead.
func (*UnblockUserResponse) Descriptor() ([]byte, []int) {
	return file_stakeholders_stakeholders_service_proto_rawDescGZIP(), []int{9}
}

func (x *UnblockUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_stakeholders_stakeholders_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_stakeholders_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_stakeholders_stakeholders_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetProfileRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UserProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	FirstName     string                 `protobuf:"bytes,5,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName      string                 `protobuf:"bytes,6,opt,name=lastName,proto3" json:"lastName,omitempty"`
	ProfileImage  string                 `protobuf:"bytes,7,opt,name=profileImage,proto3" json:"profileImage,omitempty"`
	Biography     string                 `protobuf:"bytes,8,opt,name=biography,proto3" json:"biography,omitempty"`
	Motto         string                 `protobuf:"bytes,9,opt,name=motto,proto3" json:"motto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfileResponse) Reset() {
	*x = UserProfileResponse{}
	mi := &file_stakeholders_stakeholders_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfileResponse) ProtoMessage() {}

func (x *UserProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_stakeholders_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfileResponse.ProtoReflect.Descriptor instead.
func (*UserProfileResponse) Descriptor() ([]byte, []int) {
	return file_stakeholders_stakeholders_service_proto_rawDescGZIP(), []int{11}
}

func (x *UserProfileResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserProfileResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserProfileResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserProfileResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserProfileResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UserProfileResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UserProfileResponse) GetProfileImage() string {
	if x != nil {
		return x.ProfileImage
	}
	return ""
}

func (x *UserProfileResponse) GetBiography() string {
	if x != nil {
		return x.Biography
	}
	return ""
}

func (x *UserProfileResponse) GetMotto() string {
	if x != nil {
		return x.Motto
	}
	return ""
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	ProfileImage  string                 `protobuf:"bytes,4,opt,name=profileImage,proto3" json:"profileImage,omitempty"`
	Biography     string                 `protobuf:"bytes,5,opt,name=biography,proto3" json:"biography,omitempty"`
	Motto         string                 `protobuf:"bytes,6,opt,name=motto,proto3" json:"motto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_stakeholders_stakeholders_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_stakeholders_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_stakeholders_stakeholders_service_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateProfileRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateProfileRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateProfileRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UpdateProfileRequest) GetProfileImage() string {
	if x != nil {
		return x.ProfileImage
	}
	return ""
}

func (x *UpdateProfileRequest) GetBiography() string {
	if x != nil {
		return x.Biography
	}
	return ""
}

func (x *UpdateProfileRequest) GetMotto() string {
	if x != nil {
		return x.Motto
	}
	return ""
}

type UpdateProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_stakeholders_stakeholders_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_stakeholders_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateProfileResponse) Descriptor() ([]byte, []int) {
	return file_stakeholders_stakeholders_service_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateProfileResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateProfileResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UploadProfileImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	ImagePath     string                 `protobuf:"bytes,2,opt,name=image_path,json=imagePath,proto3" json:"image_path,omitempty"` // path do slike koju je vratio ImageService
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadProfileImageRequest) Reset() {
	*x = UploadProfileImageRequest{}
	mi := &file_stakeholders_stakeholders_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadProfileImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadProfileImageRequest) ProtoMessage() {}

func (x *UploadProfileImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_stakeholders_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadProfileImageRequest.ProtoReflect.Descriptor instead.
func (*UploadProfileImageRequest) Descriptor() ([]byte, []int) {
	return file_stakeholders_stakeholders_service_proto_rawDescGZIP(), []int{14}
}

func (x *UploadProfileImageRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UploadProfileImageRequest) GetImagePath() string {
	if x != nil {
		return x.ImagePath
	}
	return ""
}

type UploadProfileImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,3,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadProfileImageResponse) Reset() {
	*x = UploadProfileImageResponse{}
	mi := &file_stakeholders_stakeholders_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadProfileImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadProfileImageResponse) ProtoMessage() {}

func (x *UploadProfileImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stakeholders_stakeholders_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadProfileImageResponse.ProtoReflect.Descriptor instead.
func (*UploadProfileImageResponse) Descriptor() ([]byte, []int) {
	return file_stakeholders_stakeholders_service_proto_rawDescGZIP(), []int{15}
}

func (x *UploadProfileImageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadProfileImageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadProfileImageResponse) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

var File_stakeholders_stakeholders_service_proto protoreflect.FileDescriptor

const file_stakeholders_stakeholders_service_proto_rawDesc = "" +
	"\n" +
	"'stakeholders/stakeholders-service.proto\"w\n" +
	"\x13RegistrationRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\"F\n" +
	"\fLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"H\n" +
	"\x16AuthenticationResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x14\n" +
	"\x12GetAllUsersRequest\"\x8c\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x1c\n" +
	"\tisBlocked\x18\x05 \x01(\bR\tisBlocked\x12\x1c\n" +
	"\tfirstName\x18\x06 \x01(\tR\tfirstName\x12\x1a\n" +
	"\blastName\x18\a \x01(\tR\blastName\x12\"\n" +
	"\fprofileImage\x18\b \x01(\tR\fprofileImage\x12\x1c\n" +
	"\tbiography\x18\t \x01(\tR\tbiography\x12\x14\n" +
	"\x05motto\x18\n" +
	" \x01(\tR\x05motto\"2\n" +
	"\x13GetAllUsersResponse\x12\x1b\n" +
	"\x05users\x18\x01 \x03(\v2\x05.UserR\x05users\"\"\n" +
	"\x10BlockUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"-\n" +
	"\x11BlockUserResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"$\n" +
	"\x12UnblockUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"/\n" +
	"\x13UnblockUserResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"/\n" +
	"\x11GetProfileRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"\xfd\x01\n" +
	"\x13UserProfileResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x1c\n" +
	"\tfirstName\x18\x05 \x01(\tR\tfirstName\x12\x1a\n" +
	"\blastName\x18\x06 \x01(\tR\blastName\x12\"\n" +
	"\fprofileImage\x18\a \x01(\tR\fprofileImage\x12\x1c\n" +
	"\tbiography\x18\b \x01(\tR\tbiography\x12\x14\n" +
	"\x05motto\x18\t \x01(\tR\x05motto\"\xc4\x01\n" +
	"\x14UpdateProfileRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1c\n" +
	"\tfirstName\x18\x02 \x01(\tR\tfirstName\x12\x1a\n" +
	"\blastName\x18\x03 \x01(\tR\blastName\x12\"\n" +
	"\fprofileImage\x18\x04 \x01(\tR\fprofileImage\x12\x1c\n" +
	"\tbiography\x18\x05 \x01(\tR\tbiography\x12\x14\n" +
	"\x05motto\x18\x06 \x01(\tR\x05motto\"K\n" +
	"\x15UpdateProfileResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"V\n" +
	"\x19UploadProfileImageRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1d\n" +
	"\n" +
	"image_path\x18\x02 \x01(\tR\timagePath\"m\n" +
	"\x1aUploadProfileImageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\timage_url\x18\x03 \x01(\tR\bimageUrl2\x80\x04\n" +
	"\x13StakeholdersService\x12=\n" +
	"\fRegisterUser\x12\x14.RegistrationRequest\x1a\x17.AuthenticationResponse\x123\n" +
	"\tLoginUser\x12\r.LoginRequest\x1a\x17.AuthenticationResponse\x128\n" +
	"\vGetAllUsers\x12\x13.GetAllUsersRequest\x1a\x14.GetAllUsersResponse\x122\n" +
	"\tBlockUser\x12\x11.BlockUserRequest\x1a\x12.BlockUserResponse\x128\n" +
	"\vUnblockUser\x12\x13.UnblockUserRequest\x1a\x14.UnblockUserResponse\x12:\n" +
	"\x0eGetUserProfile\x12\x12.GetProfileRequest\x1a\x14.UserProfileResponse\x12B\n" +
	"\x11UpdateUserProfile\x12\x15.UpdateProfileRequest\x1a\x16.UpdateProfileResponse\x12M\n" +
	"\x12UploadProfileImage\x12\x1a.UploadProfileImageRequest\x1a\x1b.UploadProfileImageResponseB\x14Z\x12proto/stakeholdersb\x06proto3"

var (
	file_stakeholders_stakeholders_service_proto_rawDescOnce sync.Once
	file_stakeholders_stakeholders_service_proto_rawDescData []byte
)

func file_stakeholders_stakeholders_service_proto_rawDescGZIP() []byte {
	file_stakeholders_stakeholders_service_proto_rawDescOnce.Do(func() {
		file_stakeholders_stakeholders_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stakeholders_stakeholders_service_proto_rawDesc), len(file_stakeholders_stakeholders_service_proto_rawDesc)))
	})
	return file_stakeholders_stakeholders_service_proto_rawDescData
}

var file_stakeholders_stakeholders_service_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_stakeholders_stakeholders_service_proto_goTypes = []any{
	(*RegistrationRequest)(nil),        // 0: RegistrationRequest
	(*LoginRequest)(nil),               // 1: LoginRequest
	(*AuthenticationResponse)(nil),     // 2: AuthenticationResponse
	(*GetAllUsersRequest)(nil),         // 3: GetAllUsersRequest
	(*User)(nil),                       // 4: User
	(*GetAllUsersResponse)(nil),        // 5: GetAllUsersResponse
	(*BlockUserRequest)(nil),           // 6: BlockUserRequest
	(*BlockUserResponse)(nil),          // 7: BlockUserResponse
	(*UnblockUserRequest)(nil),         // 8: UnblockUserRequest
	(*UnblockUserResponse)(nil),        // 9: UnblockUserResponse
	(*GetProfileRequest)(nil),          // 10: GetProfileRequest
	(*UserProfileResponse)(nil),        // 11: UserProfileResponse
	(*UpdateProfileRequest)(nil),       // 12: UpdateProfileRequest
	(*UpdateProfileResponse)(nil),      // 13: UpdateProfileResponse
	(*UploadProfileImageRequest)(nil),  // 14: UploadProfileImageRequest
	(*UploadProfileImageResponse)(nil), // 15: UploadProfileImageResponse
}
var file_stakeholders_stakeholders_service_proto_depIdxs = []int32{
	4,  // 0: GetAllUsersResponse.users:type_name -> User
	0,  // 1: StakeholdersService.RegisterUser:input_type -> RegistrationRequest
	1,  // 2: StakeholdersService.LoginUser:input_type -> LoginRequest
	3,  // 3: StakeholdersService.GetAllUsers:input_type -> GetAllUsersRequest
	6,  // 4: StakeholdersService.BlockUser:input_type -> BlockUserRequest
	8,  // 5: StakeholdersService.UnblockUser:input_type -> UnblockUserRequest
	10, // 6: StakeholdersService.GetUserProfile:input_type -> GetProfileRequest
	12, // 7: StakeholdersService.UpdateUserProfile:input_type -> UpdateProfileRequest
	14, // 8: StakeholdersService.UploadProfileImage:input_type -> UploadProfileImageRequest
	2,  // 9: StakeholdersService.RegisterUser:output_type -> AuthenticationResponse
	2,  // 10: StakeholdersService.LoginUser:output_type -> AuthenticationResponse
	5,  // 11: StakeholdersService.GetAllUsers:output_type -> GetAllUsersResponse
	7,  // 12: StakeholdersService.BlockUser:output_type -> BlockUserResponse
	9,  // 13: StakeholdersService.UnblockUser:output_type -> UnblockUserResponse
	11, // 14: StakeholdersService.GetUserProfile:output_type -> UserProfileResponse
	13, // 15: StakeholdersService.UpdateUserProfile:output_type -> UpdateProfileResponse
	15, // 16: StakeholdersService.UploadProfileImage:output_type -> UploadProfileImageResponse
	9,  // [9:17] is the sub-list for method output_type
	1,  // [1:9] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_stakeholders_stakeholders_service_proto_init() }
func file_stakeholders_stakeholders_service_proto_init() {
	if File_stakeholders_stakeholders_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stakeholders_stakeholders_service_proto_rawDesc), len(file_stakeholders_stakeholders_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stakeholders_stakeholders_service_proto_goTypes,
		DependencyIndexes: file_stakeholders_stakeholders_service_proto_depIdxs,
		MessageInfos:      file_stakeholders_stakeholders_service_proto_msgTypes,
	}.Build()
	File_stakeholders_stakeholders_service_proto = out.File
	file_stakeholders_stakeholders_service_proto_goTypes = nil
	file_stakeholders_stakeholders_service_proto_depIdxs = nil
}
