// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto/image/image-service.proto

package image

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	ImageType     string                 `protobuf:"bytes,2,opt,name=image_type,json=imageType,proto3" json:"image_type,omitempty"` // e.g., ".jpg", ".png"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageInfo) Reset() {
	*x = ImageInfo{}
	mi := &file_proto_image_image_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageInfo) ProtoMessage() {}

func (x *ImageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_image_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageInfo.ProtoReflect.Descriptor instead.
func (*ImageInfo) Descriptor() ([]byte, []int) {
	return file_proto_image_image_service_proto_rawDescGZIP(), []int{0}
}

func (x *ImageInfo) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ImageInfo) GetImageType() string {
	if x != nil {
		return x.ImageType
	}
	return ""
}

type UploadImageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to RequestData:
	//
	//	*UploadImageRequest_Info
	//	*UploadImageRequest_ChunkData
	RequestData   isUploadImageRequest_RequestData `protobuf_oneof:"request_data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageRequest) Reset() {
	*x = UploadImageRequest{}
	mi := &file_proto_image_image_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageRequest) ProtoMessage() {}

func (x *UploadImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_image_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageRequest.ProtoReflect.Descriptor instead.
func (*UploadImageRequest) Descriptor() ([]byte, []int) {
	return file_proto_image_image_service_proto_rawDescGZIP(), []int{1}
}

func (x *UploadImageRequest) GetRequestData() isUploadImageRequest_RequestData {
	if x != nil {
		return x.RequestData
	}
	return nil
}

func (x *UploadImageRequest) GetInfo() *ImageInfo {
	if x != nil {
		if x, ok := x.RequestData.(*UploadImageRequest_Info); ok {
			return x.Info
		}
	}
	return nil
}

func (x *UploadImageRequest) GetChunkData() []byte {
	if x != nil {
		if x, ok := x.RequestData.(*UploadImageRequest_ChunkData); ok {
			return x.ChunkData
		}
	}
	return nil
}

type isUploadImageRequest_RequestData interface {
	isUploadImageRequest_RequestData()
}

type UploadImageRequest_Info struct {
	Info *ImageInfo `protobuf:"bytes,1,opt,name=info,proto3,oneof"`
}

type UploadImageRequest_ChunkData struct {
	ChunkData []byte `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3,oneof"`
}

func (*UploadImageRequest_Info) isUploadImageRequest_RequestData() {}

func (*UploadImageRequest_ChunkData) isUploadImageRequest_RequestData() {}

type UploadImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageId       string                 `protobuf:"bytes,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`  //putanja u uploads/ folderu
	Size          uint32                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"` // Total size of uploaded image
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageResponse) Reset() {
	*x = UploadImageResponse{}
	mi := &file_proto_image_image_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageResponse) ProtoMessage() {}

func (x *UploadImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_image_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageResponse.ProtoReflect.Descriptor instead.
func (*UploadImageResponse) Descriptor() ([]byte, []int) {
	return file_proto_image_image_service_proto_rawDescGZIP(), []int{2}
}

func (x *UploadImageResponse) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *UploadImageResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UploadImageResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type DownloadImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadImageRequest) Reset() {
	*x = DownloadImageRequest{}
	mi := &file_proto_image_image_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadImageRequest) ProtoMessage() {}

func (x *DownloadImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_image_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadImageRequest.ProtoReflect.Descriptor instead.
func (*DownloadImageRequest) Descriptor() ([]byte, []int) {
	return file_proto_image_image_service_proto_rawDescGZIP(), []int{3}
}

func (x *DownloadImageRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type DownloadImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChunkData     []byte                 `protobuf:"bytes,1,opt,name=chunk_data,json=chunkData,proto3" json:"chunk_data,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadImageResponse) Reset() {
	*x = DownloadImageResponse{}
	mi := &file_proto_image_image_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadImageResponse) ProtoMessage() {}

func (x *DownloadImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_image_image_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadImageResponse.ProtoReflect.Descriptor instead.
func (*DownloadImageResponse) Descriptor() ([]byte, []int) {
	return file_proto_image_image_service_proto_rawDescGZIP(), []int{4}
}

func (x *DownloadImageResponse) GetChunkData() []byte {
	if x != nil {
		return x.ChunkData
	}
	return nil
}

func (x *DownloadImageResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

var File_proto_image_image_service_proto protoreflect.FileDescriptor

const file_proto_image_image_service_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/image/image-service.proto\x12\x05image\"F\n" +
	"\tImageInfo\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1d\n" +
	"\n" +
	"image_type\x18\x02 \x01(\tR\timageType\"m\n" +
	"\x12UploadImageRequest\x12&\n" +
	"\x04info\x18\x01 \x01(\v2\x10.image.ImageInfoH\x00R\x04info\x12\x1f\n" +
	"\n" +
	"chunk_data\x18\x02 \x01(\fH\x00R\tchunkDataB\x0e\n" +
	"\frequest_data\"X\n" +
	"\x13UploadImageResponse\x12\x19\n" +
	"\bimage_id\x18\x01 \x01(\tR\aimageId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x03 \x01(\rR\x04size\"2\n" +
	"\x14DownloadImageRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\"Y\n" +
	"\x15DownloadImageResponse\x12\x1d\n" +
	"\n" +
	"chunk_data\x18\x01 \x01(\fR\tchunkData\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType2\xa4\x01\n" +
	"\fImageService\x12F\n" +
	"\vUploadImage\x12\x19.image.UploadImageRequest\x1a\x1a.image.UploadImageResponse(\x01\x12L\n" +
	"\rDownloadImage\x12\x1b.image.DownloadImageRequest\x1a\x1c.image.DownloadImageResponse0\x01B\rZ\vproto/imageb\x06proto3"

var (
	file_proto_image_image_service_proto_rawDescOnce sync.Once
	file_proto_image_image_service_proto_rawDescData []byte
)

func file_proto_image_image_service_proto_rawDescGZIP() []byte {
	file_proto_image_image_service_proto_rawDescOnce.Do(func() {
		file_proto_image_image_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_image_image_service_proto_rawDesc), len(file_proto_image_image_service_proto_rawDesc)))
	})
	return file_proto_image_image_service_proto_rawDescData
}

var file_proto_image_image_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_image_image_service_proto_goTypes = []any{
	(*ImageInfo)(nil),             // 0: image.ImageInfo
	(*UploadImageRequest)(nil),    // 1: image.UploadImageRequest
	(*UploadImageResponse)(nil),   // 2: image.UploadImageResponse
	(*DownloadImageRequest)(nil),  // 3: image.DownloadImageRequest
	(*DownloadImageResponse)(nil), // 4: image.DownloadImageResponse
}
var file_proto_image_image_service_proto_depIdxs = []int32{
	0, // 0: image.UploadImageRequest.info:type_name -> image.ImageInfo
	1, // 1: image.ImageService.UploadImage:input_type -> image.UploadImageRequest
	3, // 2: image.ImageService.DownloadImage:input_type -> image.DownloadImageRequest
	2, // 3: image.ImageService.UploadImage:output_type -> image.UploadImageResponse
	4, // 4: image.ImageService.DownloadImage:output_type -> image.DownloadImageResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_image_image_service_proto_init() }
func file_proto_image_image_service_proto_init() {
	if File_proto_image_image_service_proto != nil {
		return
	}
	file_proto_image_image_service_proto_msgTypes[1].OneofWrappers = []any{
		(*UploadImageRequest_Info)(nil),
		(*UploadImageRequest_ChunkData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_image_image_service_proto_rawDesc), len(file_proto_image_image_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_image_image_service_proto_goTypes,
		DependencyIndexes: file_proto_image_image_service_proto_depIdxs,
		MessageInfos:      file_proto_image_image_service_proto_msgTypes,
	}.Build()
	File_proto_image_image_service_proto = out.File
	file_proto_image_image_service_proto_goTypes = nil
	file_proto_image_image_service_proto_depIdxs = nil
}
